### ISSUE TITLE
Issue with SIP Participant Removal Causing Persistent Ringing

### ISSUE THREAD

**Issue by symo4b** [livekit/sip#106]
When using LiveKit with SIP integration, a notable issue arises when attempting to remove a SIP participant from a call while the participant's phone is ringing. Despite successfully removing the participant from the call, the ringing persists indefinitely on the participant's end, causing confusion and potential disruption to ongoing calls.

**Steps to Reproduce:**

Initiate a call with a SIP participant using LiveKit.
While the SIP participant's phone is ringing, remove the participant programmatically or via the LiveKit interface.
Observe that although the participant is removed from the call, the ringing continues indefinitely on the participant's end.
Expected Behavior:
Upon removal of the SIP participant from the call, the ringing should cease immediately, indicating to the participant that the call has ended.

**Actual Behavior:**
After removing the SIP participant, the ringing persists indefinitely, leading to confusion and potentially disrupting ongoing calls.

**Comment by dennwc** [comment]
Should be fixed now.

**Comment by kiwijuicer** [comment]
@dennwc Is this really fixed? Where is the code-change?

We still experience ongoing outbound ringing even after remove_participant() or delete_room().
